### PR TITLE
Update Redis slave image to new location.

### LINKED ISSUE #321: kubernetes/redis-slave:v2 image does not exist
The guestbook-go example doesn't work anymore because the kubernetes/redis-slave:v2 image does not seem to exist.

```
$ kubectl logs redis-slave-8f7t2
Error from server (BadRequest): container "redis-slave" in pod "redis-slave-8f7t2" is waiting to start: image can't be pulled
```

### PR DESCRIPTION
**Pull request by nrdlngr**
Resurrecting #319 
Fixes #321

### CODE REVIEW

**Comment by nrdlngr** [comment]
I signed it.

**Comment by nrdlngr** [comment]
@idvoretskyi @sebgoa can either of you help move this PR along? The guestbook-go example has been broken for a while now, and this fixes it.

**Comment by idvoretskyi** [comment]
@nrdlngr sorry for the delay, missed out from the radar.

Approved now, should be good to go.

**Comment by nrdlngr** [comment]
Thanks @idvoretskyi!

**Pull request merged**
