### PR TITLE
Add CDK provisioner to NFS example

### PR DESCRIPTION
**Pull request by cl4u2**
Where CDK is the Charmed Distribution of Kubernetes

### CODE REVIEW

**Comment by cl4u2** [comment]
I signed it

**Comment by idvoretskyi** [comment]
@cl4u2 can you please provide more details on the purpose of the PR?

**Comment by cl4u2** [comment]
@idvoretskyi Hi, sure. In the NFS volume example, examples of PV creation in GCE and Azure's Kubernetes are provided. This PR adds a PV creation example for Charmed Distribution of Kubernetes clusters.

**Pull request merged**
