### PR TITLE
Add preempt verb for scheduler

### PR DESCRIPTION
**Pull request by resouer**
Ref: https://github.com/kubernetes/kubernetes/pull/58717

More configure examples should be added later.

### CODE REVIEW

**Comment by ahmetb** [comment]
Can you find someone from sig-scheduling to review this?

BTW We are actually trying to reduce examples in this repository. Do you have an alternative place for this to live? Such as the documentation?

**Comment by resouer** [comment]
@ahmetb Thanks. The reviewers of main repo will do review so this should not be a problem.

Emm, I think it can be placed in the doc repo but better with other configure files (existing and up coming) and other scheduler examples.

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-scheduling-pr-reviews

**Comment by k82cn** [comment]
/lgtm

+1 to @resouer , most people will try to find the configuration in some central place after reading 
 the document.

**Comment by k82cn** [comment]
btw, should we also move other scheduler config to this repo?

@ahmetb , or we have other place to do that :)

**Comment by resouer** [comment]
@bsalamat @k82cn Actually it is required to migrate examples here, the original folder will soon be deprecated and do not accept new contribute.

```
Reasons for blocking this PR:
[examples/ has moved to https://github.com/kubernetes/examples/]

examples/scheduler-policy-config-with-extender.json
```

@gyliu513 Could you please close the 59401 and migrate it to this repo?

**Comment by k82cn** [comment]
> Actually it is required to migrate examples here, the original folder will soon be deprecated and do not accept new contribute.

Great!

BTW, how do we control the version/release?

**Comment by resouer** [comment]
Version control of this repo is not clear for me.

**Comment by idvoretskyi** [comment]
@k82cn 

> BTW, how do we control the version/release?

What specifically are you interested in?

**Comment by k82cn** [comment]
The configuration maybe different between versions e.g. 1.8 vs. 1.9, how to maintain those two version of example?

**Comment by idvoretskyi** [comment]
@k82cn yes, we are going to start maintaining that soon.

**Comment by bsalamat** [comment]
> Actually it is required to migrate examples here, the original folder will soon be deprecated and do not accept new contribute.

@resouer I see. Could you or @gyliu513 use his PR that has the full list of priority and predicate functions?

**Comment by resouer** [comment]
@bsalamat I will prefer to see if @gyliu513  can move kubernetes/kubernetes#59401 to this repo first.

Because this PR is actually part of kubernetes/kubernetes#58717

**Comment by k82cn** [comment]
ping for next step :)

**Comment by ahmetb** [comment]
@bsalamat @k82cn if you're interested in being an owner for these examples, please consider creating a directory (right now these YAMLs reside in [staging/](https://github.com/kubernetes/examples/tree/master/staging) dir which is not great at all) and adding yourself as OWNERS.

**Comment by ahmetb** [comment]
@resouer UH OH, I should not have merged this.

Now we have two duplicates:

1. https://github.com/kubernetes/examples/blob/master/scheduler/scheduler-policy-config-with-extender.json
2. https://github.com/kubernetes/examples/blob/master/staging/scheduler-policy-config-with-extender.json

Can you send a PR to move (1) to (2)?

**Comment by resouer** [comment]
@ahmetb Don't worry, I will fix it.

**Pull request merged**
