### PR TITLE
Update Elasticsearch to 5.6.2

### PR DESCRIPTION
**Pull request by Jim-Lin**
- fix example file path and some log information
- modify yaml file in order to run 5.5.1

### CODE REVIEW

**Comment by Jim-Lin** [comment]
@k8s-ci-robot I signed it!

**Comment by sebgoa** [comment]
@pires do you mind taking a look here, since this is using your images ?

**Comment by pires** [comment]
Please, upgrade to latest 5.6.2 and then I'll take a look.

**Comment by Jim-Lin** [comment]
Hi @pires 
I make some change, please check it.
Thank you~~~

**Pull request merged**
