### PR TITLE
Remove stray debug echo from Makefile

### PR DESCRIPTION
**Pull request by dims**
oops #2

Change-Id: Ief434608f87afeb956a471ae35217b106a763739

### CODE REVIEW

**Comment by ahmetb** [comment]
/lgtm
do I need to run this again? :)

**Comment by mkumatag** [comment]
> /lgtm
> do I need to run this again? :)

@ahmetb I think you need to run this again, previously it was just echoing.!

**Comment by dims** [comment]
yes please @ahmetb thanks.

**Comment by ahmetb** [comment]
I ran it!

**Pull request merged**
