### PR TITLE
Update owners for k/examples

### PR DESCRIPTION
**Pull request by anonshellsllc**

### CODE REVIEW

**Comment by anonshellsllc** [comment]
I agree.  I didn't write that - it's a form, I suppose.  Don't worry on it.  Thanks! -s ---- On Sat, 18 Aug 2018 21:49:47 +0200 Ihor Dvoretskyi <notifications@github.com> wrote ---- @idvoretskyi requested changes on this pull request. I'm not sure if I see the purpose of the PR. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Slim002** [comment]
> No description provided.

**Comment by Liamtoha** [comment]
Commit

**Comment by Liamtoha** [comment]
Approve

**Pull request closed without merging**
