### PR TITLE
Update storage to v1

### PR DESCRIPTION
**Pull request by zouyee**
Update storage to v1

### CODE REVIEW

**Comment by ahmetb** [comment]
Can you also update 
https://github.com/kubernetes/website/blob/master/docs/tutorials/stateful-application/cassandra/cassandra-statefulset.yaml
https://github.com/kubernetes/website/blob/master/cn/docs/tutorials/stateful-application/cassandra-statefulset.yaml

**Comment by zouyee** [comment]
@ahmetb
My pleasure,but how to keep consistent with [kubenetes/kubernetes](https://github.com/kubernetes/kubernetes/tree/master/examples)?

**Comment by ahmetb** [comment]
> My pleasure,but how to keep consistent with kubenetes/kubernetes?

Not sure if I understand your question. We are manually updating API versions for such resources in all places when there's a change like this happens. It's part of the process, whoever is driving the feature to a new API version, they also need to make sure necessary docs/examples changes happen.

**Comment by zouyee** [comment]
by the way, I found `kubernetes/examples` is out  of   sync with `kubernetes/kubernetes/blob/master/examples` , how to keep consistency?

**Comment by ahmetb** [comment]
`kubernetes/kubernetes/blob/master/examples` is moved here as https://github.com/kubernetes/kubernetes/blob/master/examples/README.md indicates. Anything left there will be removed soon.

**Comment by ahmetb** [comment]
I see that statefulset is still v1beta2 in 1.8, so this should not be merged right away.

**Pull request merged**
