### PR TITLE
podsecuritypolicy/rbac/README.md: update to use PSP from policy API group

### PR DESCRIPTION
**Pull request by php-coder**
This is a follow-up to https://github.com/kubernetes/examples/pull/206 where I forgot to update `README.md` file.

PTAL @liggitt @tallclair
CC @simo5

### CODE REVIEW

**Comment by php-coder** [comment]
PTAL @ahmetb

**Comment by idvoretskyi** [comment]
/hold

Until 1.10 will be launched with https://github.com/kubernetes/features/issues/5 enabled.

**Comment by php-coder** [comment]
@idvoretskyi I see that Kubernetes PRs that were waiting when code freeze finishes, are merging now. Could this PR be merged also?

**Comment by php-coder** [comment]
@ahmetb PTAL

**Pull request merged**
