### PR TITLE
Migration

### PR DESCRIPTION
**Pull request by sebgoa**
This a copy of the the kubernetes/kubernetes /examples directory
Keeping the history intact.

It moves all current examples into a /staging directory to prepare for a cleanup .

### CODE REVIEW

**Comment by sebgoa** [comment]
@ahmetb @bgrant0607 

checking who I need to properly @mention: @kubernetes/sig-contributor-experience-misc 

I think we need to get this merged quickly, and head over to the main repo to do the redirects.

**Comment by sebgoa** [comment]
not sure why the CLA check is failing here, I have signed it at least twice.

**Comment by cblecker** [comment]
The CLA is failing due to many commits from many authors here.

**Comment by sebgoa** [comment]
ok, in agreement with Brian, the history is preserved from the original kubernetes/examples ...

**Comment by bgrant0607** [comment]
Thanks for maintaining the history. If something looks wrong, we can always nuke it and start over, but it will be easiest to check after this is merged.

Yes, CLA bots aren't expected to deal with this, much like bulk cherrypicks into release branches. The original commits were verified to be covered by the CLA.

Merging.

**Comment by bgrant0607** [comment]
Confirmed that "blame" worked on a couple of the files.

Note that git history works but github PR history won't show the earlier PRs.

**Comment by liggitt** [comment]
> It moves all current examples into a /staging directory to prepare for a cleanup .

is the cleanup still planned? https://github.com/kubernetes/kubernetes/pull/80356/files is attempting to update links to things in this subfolder folder, but I'm not sure why it exists

**Pull request merged**
