### PR TITLE
Update language yaml

### PR DESCRIPTION
**Pull request by EmilyM1**
Addressing https://github.com/kubernetes/examples/issues/415

This PR will remove offensive and antiquated slave terminology. Will go with replica as it's db appropriate.

Will update instances and file names, won't touch the image names ex: k8s.gcr.io/{name}. I am not the image owner and that change will trigger some broken code examples.

Update:
This should be ready for review. Some things are not within my rights to change as I am not the owner such as:
Images - image names not changed
Config files - these are upstream from k8s
Shell Script commands - unsure on the regression issues on changing these

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@EmilyM1 Is this still in progress?

**Comment by EmilyM1** [comment]
@idvoretskyi should be ready for review

**Review by idvoretskyi — APPROVED** [review]
/lgtm

/approve

**Pull request merged**
