### PR TITLE
Add controller required for tests in kubernetes/kubernetes

### PR DESCRIPTION
**Pull request by aledbf**
This file is used in several tests in kubernetes/kubernetes

### CODE REVIEW

**Comment by ahmetb** [comment]
This came up before, our status on tests is that they should host such YAML files.
"examples" repo is not for hosting test files.

**Comment by ahmetb** [comment]
Can you explain why you can't remove them more clearly? I'm not aware of the situation. Are the tests failing?

We already have the manifest in kubernetes/website repo unless I'm mistaken. But we should probably consider the image as the _output_ of this repo, and we should put the test manifest to wherever the test is (tests often do customizations that do not concern anyone else).

**Comment by aledbf** [comment]
> (tests often do customizations that do not concern anyone else).

Good point. This is exactly what is happening in the tests located in k/k.
I will close this PR and copy the file near the tests that require the manifest.

**Pull request closed without merging**
