### PR TITLE
Update wordpress to 4.8.1

### PR DESCRIPTION
**Pull request by netroby**

### CODE REVIEW

**Comment by ahmetb** [comment]
@netroby Do we really care this is 4.7 vs 4.8 for the purposes of this tutorial? Why don't we just call it `wordpress:4` instead?

Are you familiar with WordPress enough to comment whether minor differences matter or not? My thinking is that minor versions (and upgrades between them) should be fine, so I am not too worried about just specifying this as `:4`. Not to mention, this is mostly a tutorial, people can use the Helm chart (https://kubeapps.com/charts/stable/wordpress) to deploy it more reliably.

**Comment by netroby** [comment]
The big version may not working. but the small version upgrade shall be fine. I will take long watch the wordpress upgrade progress.

**Comment by ahmetb** [comment]
@netroby I guess I can clarify. If wordpress follows http://semver.org for versioning, when you specify `wordpress:4` it will pick up the largest wordpress 4.x, which may contain feature differences; but not breaking changes.

If we do not trust that, we should use `wordpress:4.8`. Using `4.8.1` is far too specific and it means you'll not get bugfixes, and even the security patches (such as 4.8.2). If you can change the patch to `:4.8` I think we're ok.

**Comment by netroby** [comment]
@ahmetb Hello, I make it to 4.8

**Comment by ahmetb** [comment]
/lgtm
Thanks.

**Pull request merged**
