### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by laurilehmijoki**

### CODE REVIEW

**Comment by sebgoa** [comment]
@laurilehmijoki have you signed the CNCF CLA ?

**Comment by xiangpengzhao** [comment]
@laurilehmijoki thanks for the contribution! Please sign the CLA before we can merge this PR :)

**Comment by sebgoa** [comment]
@laurilehmijoki as we try to get higher quality and more significant PRs, would you mind reviewing the entire example, making sure it works well. Maybe there are other typos, or clarifications to bring to the example.

thanks

**Comment by laurilehmijoki** [comment]
Closing to PR due to my other commitments.  Thanks for Kubernetes!

**Pull request closed without merging**
