### PR TITLE
Update guestbook example to remove inappropriate terminology

### PR DESCRIPTION
**Pull request by paulczar**
The guestbook and redis documentation are littered with master/slave terminology. This update along with the update to the [website](https://github.com/kubernetes/website/pull/22934) removes that terminology and technology.

Addresses https://github.com/kubernetes/website/issues/22918

Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

### CODE REVIEW

**Comment by paulczar** [comment]
We need a more appropriate place to host the built docker image as I don't have access to the original google repository, and it shouldn't be hosted in my personal one.

**Comment by justinsb** [comment]
I do approve of fixing the naming, but this seems to replace redis with mongodb ... that's a pretty big change.

Maybe we make this into a new example, and we take another pass at this idea to rename to leader & follower (are those the right terms here?)

**Comment by justaugustus** [comment]
Closing in favor of https://github.com/kubernetes/examples/pull/410.
/close

**Pull request closed without merging**
