### PR TITLE
Correct GlusterFS description with proper upstream URLs.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@sebgoa please review , Thanks !

**Comment by sebgoa** [comment]
Can you bundle several commits like this in a single PR. That would save time.

I will wait for you to add more glusterFS changes to merge everything at once.

thanks

**Comment by humblec** [comment]
@sebgoa this was accidentally noticed after submitting the first PR. Otherwise I would have clubbed both and I am done atleast for now.

**Pull request merged**
