### PR TITLE
Update README with new supported SC parameters.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by ahmetb** [comment]
Can you please find someone familiar with glusterfs support (or someone from the sig-storage) to approve this? I'm not the subject-matter expert to approve the contents of this PR are indeed accurate.

**Comment by humblec** [comment]
@ahmetb I belong to approver for GlusterFS. Any way I have added @jsafrane

**Comment by jsafrane** [comment]
/lgtm
fro sig-storage point of view

**Pull request merged**
