### PR TITLE
Add "Storage Policy Management for containers" to vSphere docs

### PR DESCRIPTION
**Pull request by BaluDontu**
Add content for using Storage Policy Management for containers using vSphere Cloud Provider.

### CODE REVIEW

**Comment by BaluDontu** [comment]
@ahmetb can you please take a look at this content and merge it if everything looks good.

**Comment by ahmetb** [comment]
Looking for an additional reviewer to /lgtm this. Can you recommend anyone, if not we can `@` the sig-storage-reviewers team?

**Comment by BaluDontu** [comment]
I would recommend going with sig-storage-reviewers team.

**Comment by ahmetb** [comment]
@kubernetes/sig-storage-pr-reviews Can someone review this PR (sorry for broad communication).

**Comment by jsafrane** [comment]
lgtm from sig-storage point of view

**Pull request merged**
