### PR TITLE
Add Azure Disk-based NFS volume option

### PR DESCRIPTION
**Pull request by hosungsmsft**
We'd like this example to include an option to do the same on Azure with an Azure Disk-based persistent volume, so here goes this PR.

Sorry that I haven't looked how CI works here, and I'll fix any issues as this PR goes along.

Thanks,
Hosung Song

### CODE REVIEW

**Comment by hosungsmsft** [comment]
A new comment to trigger another CLA verification

**Comment by idvoretskyi** [comment]
cc @k8s-mirror-azure-pr-reviews

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-azure-misc

**Pull request merged**
