### PR TITLE
Migrate kubernetes/kubernetes/examples

### PR DESCRIPTION
**Pull request by sebgoa**
PR to migrate the examples to dedicated kubernetes/examples repo.

This preserves history.

Cleanup of source in kubernetes/kubernetes will happen after this gets merged.

### CODE REVIEW

**Comment by sebgoa** [comment]
@k8s-bot test this

**Comment by ahmetb** [comment]
I'm currently -1 for moving all existing examples here. We have a chance to do a clean start and we are planning to keep only "tutorial examples" in this repository. Let’s hold off on shuffling code around until we have a clean path forward. I’ll set up a Hangouts meeting with SIG-Apps sometime this week.

**Comment by ahmetb** [comment]
After the discussion on https://groups.google.com/d/msgid/kubernetes-sig-apps/CACZ5N2amx9GUbXM%2BokJ%3DBB%2BWZu0scir2GWwwFguj-T43LokRVg%40mail.gmail.com?utm_medium=email&utm_source=footer I think we can move forward with this.

Once merged, we should probably find a way to reorganize the content in this repository and make proper redirections in the original repository (not sure about the order). Then we can evaluate each of the examples (most of them were already evaluated in my proposal) and stage each one for deletion. We can probably try to contact the owners of each example and encourage them to move things to their own repo.

**Comment by ahmetb** [comment]
Also, I am planning to move README.md files of maintained examples (guestbook ones, wordpress-mysql and cassandra) to the docs repository and link back here for the .yaml files. The new README.md files of these maintained examples would be just links to the k8s.io website.

Most of the stuff in volumes/ can probably moved to documentation repo as they are actually just serving documentation purposes and they are neither usable out of the box nor full examples.

**Comment by sebgoa** [comment]
I am closing this one right now, and I am making a fresh one shortly.
I will move everything to /staging

**Pull request closed without merging**
