### PR TITLE
Use fixed NFS dns name

### PR DESCRIPTION
**Pull request by IronPan**

### CODE REVIEW

**Comment by sdanbury** [comment]
@IronPan apologies to mention you randomly. Does k8s handle the NFS server DNS lookup nicely now? Up until now, you have had to specify the IP of the nfs service, rather than reference the DNS name. For example: https://github.com/kubernetes/minikube/issues/3417.

**Comment by ensonic** [comment]
Still does not work. See
https://github.com/kubernetes/minikube/issues/3417

**Comment by adthonb** [comment]
Still doesn't work with DNS, use Service's Cluster-IP instead.

**Pull request merged**
