### PR TITLE
Use docker to build cassandra jar file

### LINKED ISSUE #147: Cassandra: example does not use KubernetesSeedProvider while doc says it does
From the Kubernetes documentation (https://kubernetes.io/docs/tutorials/stateful-application/cassandra/), we can read this statement:

` In this instance, a custom Cassandra SeedProvider enables Cassandra to discover new Cassandra nodes as they join the cluster.`

However the example does not seem to use the KubernetesSeedProvider.

On the KubernetesSeedProvider Readme:

` This provider is bundled with the Docker provided in this example.`

Therefore I set the environment variable as follow in the statefulset.yaml, to try to force it to use KubernetesSeedProvider:

`          - name: CASSANDRA_SEED_PROVIDER
            value: "org.apache.cassandra.locator.KubernetesSeedProvider"`

I got this error:

`java.lang.ClassNotFoundException: org.apache.cassandra.locator.KubernetesSeedProvider`

Can we either fix the documentation or fix the code so that it uses the KubernetesSeedProvider? Seems we are not making use of it

### LINKED ISSUE #190: KubernetesSeedProvider: endpoints null for first node
https://github.com/kubernetes/examples/blob/8774c894fa623dcc7a43bdfdc4fbf5668074fadf/cassandra/java/src/main/java/io/k8s/cassandra/KubernetesSeedProvider.java#L134-L137

Regarding this comment, are there any other scenarios in which ```endpoints``` can be null? If not, possibly the local ip could be placed in the seed list instead of using the default seeds list.

### PR DESCRIPTION
**Pull request by aledbf**
Test image: `aledbf/cassandra:v15`

This PR also replaces the java code with a go shared library.

fixes #190 
fixes #147

### CODE REVIEW

**Comment by ahmetb** [comment]
It'd be great if you can find someone else who knows cassandra a little bit better to review this, perhaps someone from sig-storage can help.

**Comment by ahmetb** [comment]
If this is good to go, do you mind finding a reviewer (perhaps the original developers of Cassandra example, or we can mention [@]kubernetes/sig-storage-pr-reviews).

**Comment by ahmetb** [comment]
Sorry I was late to review this. I don't understand the domain much but the code looks good + you're the owner for this example now.
/lgtm

**Comment by ahmetb** [comment]
@aledbf Let me know the image needs re-pushing.

**Comment by aledbf** [comment]
@ahmetb yes, you need to publish the image.

**Comment by ahmetb** [comment]
@aledbf this fails to build:

```
/build.sh: line 33: CASSANDRA_VERSION: unbound variable
The command '/bin/sh -c clean-install bash     && /build.sh     && rm /build.sh' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
```

**Comment by ahmetb** [comment]
My bad I probably should've used the makefile to build/push.

**Comment by ahmetb** [comment]
I pushed `gcr.io/google-samples/cassandra:v14` (+`-dev`) please try out and update the documentation.

**Comment by aledbf** [comment]
> but the addition of a Go shared library makes it more difficult for us to re-use this in Navigator.

Why?

> Hi @aledbf. What was the motivation for introducing the Go shared library?

Because doing this in go is cleaner than the previous code and also we can use client-go

**Comment by madireddyr** [comment]
@aledbf : when we tried gcr.io/google-samples/cassandra:v14 & 13 : we got below error 
INFO 19:45:59 Unable to load cassandra-topology.properties; compatibility mode disabled
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: io.k8s.cassandra.KubernetesSeedProvider
Fatal configuration error; unable to start server. See log for stacktrace.
org.apache.cassandra.exceptions.ConfigurationException: io.k8s.cassandra.KubernetesSeedProvider
Fatal configuration error; unable to start server. See log for stacktrace.
at org.apache.cassandra.config.DatabaseDescriptor.applySeedProvider(DatabaseDescriptor.java:895)
at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:324)
at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:142)
at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:647)
at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:582)
at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691)
ERROR 19:45:59 Exception encountered during startup
org.apache.cassandra.exceptions.ConfigurationException: io.k8s.cassandra.KubernetesSeedProvider
Fatal configuration error; unable to start server. See log for stacktrace.
at org.apache.cassandra.config.DatabaseDescriptor.applySeedProvider(DatabaseDescriptor.java:895) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:324) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:142) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:647) [apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:582) [apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691) [apache-cassandra-3.11.2.jar:3.11.2]

i tried above example with aledbf/cassandra:v15 and it worked . not sure whats the difference between
gcr.io/google-samples/cassandra:v14 & aledbf/cassandra:v15

i see aledbf/cassandra:v15 got merged could you point me committed image(seems aledbf/cassandra:v15 is a test image)

**Comment by mkobit** [comment]
@madireddyr It doesn't look like the `gcr.io/google-samples/cassandra:v14` tag was updated with these changes

**Pull request merged**
