### PR TITLE
Bump image versions in selenium example

### PR DESCRIPTION
**Pull request by reegnz**

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@reegnz any specific reasons to change the image versions here?

**Comment by reegnz** [comment]
I changed it so the example uses the same image versions as the documentation at https://github.com/SeleniumHQ/docker-selenium 

Also the 3.11 images were last built 6 months ago, there have been a few Chrome and Firefox releases since then. 3.14 contains the latest stable browser versions.

**Comment by ahmetb** [comment]
@reegnz have you tested this manually? If so, I don't see a reason why we can't approve.

**Pull request merged**
