### PR TITLE
Update guidelines.md

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by ahmetb** [comment]
I think the `cluster/kubectl.sh` note is pretty obsolete at this point. Can you please remove this item completely?

**Comment by hzxuzhonghu** [comment]
@ahmetb ok, i will remove it.

**Comment by ahmetb** [comment]
Sorry, I meant to remove this sentence altogether. kubectl is pretty much the only option, so saying "Use kubectl" alone sounds a bit strange.

**Comment by hzxuzhonghu** [comment]
ok, I know

**Comment by ahmetb** [comment]
Thank you!
/lgtm

**Pull request merged**
