### PR TITLE
Provide a more ideal example for scheduler extender policy.

### PR DESCRIPTION
**Pull request by mindprince**
We now use default predicates/priorities if they are unspecified in the policy
config (kubernetes/kubernetes#59363).

The other example in ./scheduler-policy-config.json shows how to use priorities
and predicates.

Let's use this example to show how to use extenders. When you are using
extenders you don't necessarily want to mess with priorities and predicates
(kubernetes/kubernetes#45188).

This was previously kubernetes/kubernetes#62186

### CODE REVIEW

**Comment by mindprince** [comment]
/assign @ahmetb 

This was LGTM'd in https://github.com/kubernetes/kubernetes/pull/62186

**Comment by mindprince** [comment]
/hold

I am confused, why is there duplication:
https://github.com/kubernetes/examples/blob/master/scheduler/scheduler-policy-config-with-extender.json
https://github.com/kubernetes/examples/blob/master/staging/scheduler-policy-config-with-extender.json

Maybe I should just wait for the move from kubernetes/kubernetes to kubernetes/examples to complete before making any changes.

**Comment by ahmetb** [comment]
@mindprince yeah we just made a mistake earlier today: https://github.com/kubernetes/examples/pull/205#issuecomment-379825170

I'm waiting for a PR from @resouer to move this file to `staging/`.

**Comment by resouer** [comment]
I am working on it, will send it out today.

**Comment by mindprince** [comment]
You don't need to anymore.

**Comment by resouer** [comment]
Thanks!

**Pull request merged**
