### PR TITLE
Add details on mounting existing Azure Managed Disks

### PR DESCRIPTION
**Pull request by noelbundick**
This PR adds examples for how to use preexisting Managed Disks with Pods

The information was gathered from the following sources:
* [AzureDiskVolumeSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#azurediskvolumesource-v1-core)
* [validation.go](https://github.com/kubernetes/kubernetes/blob/ae1fc13aee81e66b9b74a5fb881ff3f90463ff4e/pkg/apis/core/validation/validation.go#L1291)
* [types.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L1365)
* [Volumes with Azure Disks](https://docs.microsoft.com/en-us/azure/aks/azure-disk-volume)

### CODE REVIEW

**Comment by noelbundick** [comment]
check CLA

**Comment by noelbundick** [comment]
@khenidak, could you help me get a review on this?

**Comment by khenidak** [comment]
@idvoretskyi @ahmetb sebgoa
/lgtm -- but we need your approval guys. Thanks!

**Pull request merged**
