### PR TITLE
delete kubectl-container

### PR DESCRIPTION
**Pull request by ahmetb**
This is not an example and was here when we were releasing the
gcr.io/google_containers/kubectl image actively (stopped doing that in 2015).
This is now unused and does not work, therefore removing.

/cc @sebgoa

### CODE REVIEW

**Comment by ahmetb** [comment]
/assign @sebgoa 
thoughts?

**Comment by ahmetb** [comment]
@sebgoa ping

**Comment by sebgoa** [comment]
there is a reference to it here: https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

so remove that from the docs and yes we can delete this :)

**Comment by ahmetb** [comment]
Yes I actually saw this there.

**Comment by sebgoa** [comment]
ok so /lgtm but if we merge this the docs will get broken.

**Comment by ahmetb** [comment]
Agreed, will merge after fixing docs.

**Comment by ahmetb** [comment]
https://github.com/kubernetes/website/pull/6713

**Comment by ahmetb** [comment]
This is now good to go.

**Pull request merged**
