### PR TITLE
Migrate k8s.gcr.io to registry.k8s.io

### PR DESCRIPTION
**Pull request by vaibhav2107**
With ref to [kubernetes/k8s.io#4738](https://github.com/kubernetes/k8s.io/issues/4738)

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @aledbf @soltysh 
Could you please have a look

**Comment by vaibhav2107** [comment]
Thanks @stmcginnis

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
