### PR TITLE
https-nginx: Correct tls.[crt|key] mount

### LINKED ISSUE #194: Incompatible certificate name
Your `nginx.conf` file points the certs to `nginx.cert` and `nginx.key`, while your inside the mount point they are called `tls.cert` and `tls.key`.

### PR DESCRIPTION
**Pull request by ahmetb**
Fixes #194.

### CODE REVIEW

**Comment by ahmetb** [comment]
@idvoretskyi Thanks! We still haven't enabled auto-merging. Do you know how we can get that?

**Comment by idvoretskyi** [comment]
@ahmetb just got a few instructions from @ixdy - it's easy as sampled here https://github.com/kubernetes/test-infra/pull/6969

**Pull request merged**
